name: coded_shots
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.4.10
  flutter_animate: ^4.5.0
  fpdart: ^1.1.0
  phosphor_flutter: ^2.0.1
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  # cached_network_image: ^3.3.1
  animations: ^2.0.11
  flextras: ^1.0.0
  skeletonizer: ^1.0.1
  # firebase_core: ^2.25.4
  # firebase_storage: ^11.6.5
  # cloud_firestore: ^4.15.4
  # firebase_auth: ^4.17.4
  uuid: ^4.3.3
  responsive_builder: ^0.7.0
  flutter_screenutil: ^5.9.0
  cool_dropdown: ^2.1.0
  gap: ^3.0.1
  flutter_portal: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
